version: '3'

services:
#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
#      MYSQL_DATABASE: test_db
#      MYSQL_USER: devuser
#      MYSQL_PASSWORD: devpass
#    ports:
#      - "9906:3306"

  db:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      #      ports:
      #        - "3306:3306"
      #    image: php:7.2.2-apache

      #    image: php:5.6-apache

  web:
    container_name: php_web
    build:
      context: ./php
    #    command: docker-php-ext-install mysqli
    volumes:
        #      - ./php/:/var/www/html/
        - ./:/var/www/html/
    depends_on:
        - db
    ports:
        #      - "8100:80"
        - "80:80"
    stdin_open: true
    tty: true


  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080