version: '3'

services:
#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
#      MYSQL_DATABASE: test_db
#      MYSQL_USER: devuser
#      MYSQL_PASSWORD: devpass
#    ports:
#      - "9906:3306"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  web:
#    image: php:7.2.2-apache
    image: php:5.6-apache
    container_name: php_web
#    command: docker-php-ext-install mysqli
    depends_on:
      - db
    volumes:
#      - ./php/:/var/www/html/
      - ./:/var/www/html/
    ports:
#      - "8100:80"
      - "80:80"
    stdin_open: true
    tty: true

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080